import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.scss";
import { Header } from "@/components/shared/header";

const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Next Pizza | Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={nunito.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
